modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LoveTropics/LTDonations/issues"
license = "All Rights Reserved"

[[mods]]
modId="ltdonations"
version="${mod_version}"
displayName="LTDonations"
displayURL="https://lovetropics.com"
credits=""
authors="tterrag, Corosus"
description='''
Donation event manager for the LoveTropics livestream.
'''
