modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/LoveTropics/LTDonations/issues"
license = "Mozilla Public License Version 2.0"

[[mods]]
modId="ltdonations"
version="${mod_version}"
displayName="LTDonations"
displayURL="https://lovetropics.com"
authors="The Love Tropics Team"
description='''
Donation event manager for the LoveTropics livestream.
'''

[[mixins]]
config = "ltdonations.mixins.json"
